Guest/urls.py
from django.urls import path
from Guest import views
app_name='guest'

urlpatterns = [
    path('home/',views.home,name="Home"),
    path('newuser/',views.newuser,name="Newuser"),
    path('ajax_place/',views.ajaxplace,name="Ajax_Place"),
    path('login/',views.login,name="Login"),
    path('newagency/',views.newagency,name="NewAgency"),
]

MissionSeeker/urls.py
from django.contrib import admin
from django.urls import path,include

from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('WebAdmin/',include('Admin.urls')),
    path('agency/',include('Agency.urls')),
    path('user/',include('User.urls')),
    path('guest/',include('Guest.urls')),
    path('',views.home,name="Home"),
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views
app_name='user'

urlpatterns = [
    path('homeuser/',views.userhome,name="User-Home"),
    path('userprofile/',views.uprofile,name="User_Profile"),
    path('editprof/<int:euid>',views.ueditprof,name="U_EditProfile"),
    path('changepass/<int:cuid>',views.uchangepass,name="U_ChangePwd"),
    path('ucomplaint/',views.UComplaint,name="UComplaint"),
    path('search_agency/',views.SearchAg,name="SearchAgency"),
    path('get_agency/',views.getAgency,name="GetAgency"),
    path('crime/<int:aid>',views.crime,name="Crime"),
    path('Key/<int:cid>', views.keyverification, name="User_Key"),
    path('Chat/', views.chatuser, name="Chat-user"),
    path('loadchat/', views.loadchatuser, name="load-chat"),
]

Guest/models.py
from enum import unique
from django.db import models
from Admin.models import *

# Create your models here.

class NewUser(models.Model):
    name=models.CharField(max_length=50)
    contact=models.CharField(max_length=50)
    email=models.EmailField(unique=True)
    address=models.TextField(null=True)
    gender=models.CharField(max_length=50)
    place=models.ForeignKey(Place,on_delete=models.CASCADE)
    password=models.CharField(unique=True,max_length=50)
    key=models.BinaryField(max_length=1000,null=True)
    
class NewAgency(models.Model):
    ag_name=models.CharField(max_length=50)
    ag_email=models.EmailField(unique=True)
    ag_logo=models.FileField(upload_to='agencydocs/')
    ag_proof=models.FileField(upload_to='agencydocs/')
    ag_password=models.CharField(unique=True,max_length=50)
    crimetype=models.ForeignKey(CrimeType,on_delete=models.CASCADE)
    ag_status=models.IntegerField(default=False)
    keys=models.BinaryField(max_length=1000,null=True)
   
    

Guest/views.py
from django.shortcuts import render,redirect
from cryptography.fernet import Fernet
from Guest.models import *
from Admin.models import *
from django.conf import settings
from django.core.mail import send_mail
# Create your views here.

def home(request):
    return render(request,"Guest/Home.html")

def newuser(request):
    dist=District.objects.all()
    if request.method=="POST":
        genwrite_key()
        plcid=request.POST.get('sel_plc')
        plc=Place.objects.get(id=plcid)
        name=request.POST.get('txt_name')
        email1=request.POST.get('txt_email')
        key = call_key()
        str1=key.decode()
        send_mail(
            'Respected sir/madam '+name, #subject
            "\r Your Encryption Key is "+str1+"Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        NewUser.objects.create(name=request.POST.get('txt_name'),contact=request.POST.get('txt_cntct'),
        email=request.POST.get('txt_email'),address=request.POST.get('txt_address'),gender=request.POST.get('gender'),
        place=plc,password=request.POST.get('txt_pwd'),key=key)
        return render(request,"Guest/NewUser.html",{'Dis':dist})
    else:
        return render(request,"Guest/NewUser.html",{'Dis':dist})
    
def ajaxplace(request):
    dist=request.GET.get('district')
    plc=Place.objects.filter(district=dist)
    return render(request,"Guest/AjaxPlace.html",{'PLC':plc})

def login(request):
    if request.method=="POST":
        
        Email=request.POST.get('txt_email')
        Password=request.POST.get('txt_pass')
        adminlog=Admin.objects.filter(email=Email,password=Password).count()
        userlog=NewUser.objects.filter(email=Email,password=Password).count()
        agencylog=NewAgency.objects.filter(ag_email=Email,ag_password=Password,ag_status=True).count()
        if adminlog > 0:
            admin=Admin.objects.get(email=Email,password=Password)
            request.session['aid']=admin.id
            return redirect('webadmin:Admin-Home')
        elif userlog > 0:
            user=NewUser.objects.get(email=Email,password=Password)
            request.session['uid']=user.id
            return redirect('user:User-Home')
        elif agencylog > 0:
            agency=NewAgency.objects.get(ag_email=Email,ag_password=Password,ag_status=1)
            request.session['agid']=agency.id
            return redirect('agency:Agency-Home')
        else:
            error="Invalid Details"
            return render(request,"Guest/Login.html",{"Error":error})
    else:
        return render(request,"Guest/Login.html")
    
def newagency(request):
    ctype=CrimeType.objects.all()
    if request.method=="POST" and request.FILES:
        genwrite_key()
        ctid=request.POST.get('sel_crimetype')
        ct=CrimeType.objects.get(id=ctid)
        name=request.POST.get('txt_name')
        email1=request.POST.get('txt_email')
        key = call_key()
        str1=key.decode()
        send_mail(
            'Respected sir/madam '+name, #subject
            "\r Your Encryption Key is "+str1+"Thank you.",#body
            settings.EMAIL_HOST_USER,
            [email1],

        )
        NewAgency.objects.create(ag_name=request.POST.get('txt_name'),ag_email=request.POST.get('txt_email'),
        ag_logo=request.FILES.get('logo'),ag_proof=request.FILES.get('proof'),ag_password=request.POST.get('txt_pass'),
        crimetype=ct,keys=key)  
        return render(request,"Guest/NewAgency.html",{'CT':ctype}) 
    else: 
        return render(request,"Guest/NewAgency.html",{'CT':ctype})
    



def genwrite_key():
    key = Fernet.generate_key()
    with open("pass.key", "wb") as key_file:
        key_file.write(key)

def call_key():
    return open("pass.key", "rb").read()

Guest/templates/Guest/AjaxPlace.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajax_Place</title>
</head>
<body>
    <option value="">----select----</option>
    {% for i in PLC %}
      <option value="{{i.id}}">{{i}}</option>
    {% endfor %}
</body>
</html>

Guest/templates/Guest/Head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<!-- For IE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<!-- For Resposive Device -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>BizPro || Responsive html5 template</title>

		<!-- Favicon -->
		<link rel="icon" type="image/png" sizes="56x56" href="{% static 'Main/images/fav-icon/icon.png' %}">


		<!-- Main style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'Main/css/style.css' %}">
		<link rel="stylesheet" href="{% static 'Form/form.css' %}">
		<!-- responsive style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'Main/css/responsive.css' %}">


		<!-- Fix Internet Explorer ______________________________________-->

		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
			<script src="vendor/html5shiv.js"></script>
			<script src="vendor/respond.js"></script>
		<![endif]-->
			
	</head>

	<body>
		<div class="main-page-wrapper">



			<!-- 
			=============================================
				Theme Header
			============================================== 
			-->
			<header class="theme-main-header" style="background-color:black;">
				<div class="container">
					<a href="index.html" class="logo float-left tran4s"><img src="" alt=""></a>
					
					<!-- ========================= Theme Feature Page Menu ======================= -->
					<nav class="navbar float-right theme-main-menu one-page-menu">
					   <!-- Brand and toggle get grouped for better mobile display -->
					   <div class="navbar-header">
					     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
					       <span class="sr-only">Toggle navigation</span>
					       Menu
					       <i class="fa fa-bars" aria-hidden="true"></i>
					     </button>
					   </div>
					   <!-- Collect the nav links, forms, and other content for toggling -->
					   <div class="collapse navbar-collapse" id="navbar-collapse-1">
					     <ul class="nav navbar-nav">
					       	<li class="active"><a href="{% url 'guest:Home' %}">HOME</a></li>
							<li><a href="{% url 'guest:Login' %}">Login</a></li>
							<li><a href="{% url 'guest:Newuser' %}">NewUser Registration</a></li>
							<li><a href="{% url 'guest:NewAgency' %}">NewAgency Registartion</a></li>
							{% comment %} <li><a href="#team-section">TEAM</a></li>
							<li><a href="#skill-section">Skill</a></li>
							<li><a href="#our-client">CLIENTS</a></li>
							<li><a href="#pricing-section">Pricing</a></li>
							<li class="dropdown-holder"><a href="#blog-section">BLOG</a>
								<ul class="sub-menu">
					       			<li><a href="blog-details.html" class="tran3s">Blog Details</a></li>
					       		</ul>
							</li>
							<li><a href="#contact-section">CONTACT</a></li> {% endcomment %}
					     </ul>
					   </div><!-- /.navbar-collapse -->
					</nav> <!-- /.theme-feature-menu -->
				</div>
			</header> <!-- /.theme-main-header -->


			<!--
			=====================================================
				Theme Main SLider
			=====================================================
			-->
			
									{% block content %}

                                    {% endblock content %}

                                

                    <!--
			=====================================================
				Footer
			=====================================================
			-->
			<footer>
				<div class="container">
					<a href="index.html" class="logo"><img src="" alt=""></a>

					<ul>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-flickr" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
					</ul>
					<p>Copyright @2018 All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
				</div>
			</footer>




			<!-- =============================================
				Loading Transition
			============================================== -->
			<div id="loader-wrapper">
				<div id="preloader_1">
	                <span></span>
	                <span></span>
	                <span></span>
	                <span></span>
	                <span></span>
	            </div>
			</div>

			
	        <!-- Scroll Top Button -->
			<button class="scroll-top tran3s p-color-bg">
				<i class="fa fa-long-arrow-up" aria-hidden="true"></i>
			</button>




		<!-- Js File_________________________________ -->

		<!-- j Query -->
		<script type="text/javascript" src="{% static 'Main/vendor/jquery.2.2.3.min.js' %}"></script>

		<!-- Bootstrap JS -->
		<script type="text/javascript" src="{% static 'Main/vendor/bootstrap/bootstrap.min.js' %}"></script>

		<!-- Vendor js _________ -->
		
		<!-- revolution -->
		<script src="{% static 'Main/vendor/revolution/jquery.themepunch.tools.min.js' %}"></script>
		<script src="{% static 'Main/vendor/revolution/jquery.themepunch.revolution.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.slideanims.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.layeranimation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.navigation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.kenburn.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.actions.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.video.min.js' %}"></script>

		<!-- Google map js -->
		<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZ8VrXgGZ3QSC-0XubNhuB2uKKCwqVaD0&callback=goMap" type="text/javascript"></script> <!-- Gmap Helper -->
		<script src="{% static 'Main/vendor/gmaps.min.js' %}"></script>
		<!-- owl.carousel -->
		<script type="text/javascript" src="{% static 'Main/vendor/owl-carousel/owl.carousel.min.js' %}"></script>
		<!-- mixitUp -->
		<script type="text/javascript" src="vendor/jquery.mixitup.min.js' %}"></script>
		<!-- Progress Bar js -->
		<script type="text/javascript" src="vendor/skills-master/jquery.skills.js' %}"></script>
		<!-- Validation -->
		<script type="text/javascript" src="vendor/contact-form/validate.js' %}"></script>
		<script type="text/javascript" src="vendor/contact-form/jquery.form.js' %}"></script>


		<!-- Theme js -->
		<script type="text/javascript" src="{% static 'Main/js/theme.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/js/map-script.js' %}"></script>

		</div> <!-- /.main-page-wrapper -->
	</body>
</html>

Guest/templates/Guest/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V18</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'Login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'Login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Login/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body style="background-color: #666666;">
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="post">
                    {% csrf_token %}
					<span class="login100-form-title p-b-43"><b style="font-family: 'Times New Roman', Times, serif;">
						Login to continue
					</b></span>
					
					
					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="email" name="txt_email" autocomplete="off">
						<span class="focus-input100"></span>
						<span class="label-input100">Email</span>
					</div>
					
					
					<div class="wrap-input100 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="txt_pass">
						<span class="focus-input100"></span>
						<span class="label-input100">Password</span>
					</div>

					<div class="flex-sb-m w-full p-t-3 p-b-32">
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							{% comment %} <label class="label-checkbox100" for="ckb1">
								Remember me
							</label> {% endcomment %}
						</div>

						<div>
							<a href="{% url 'guest:Home' %}" class="txt1">
								Home
							</a>
						</div>
					</div>
			

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" name="login" style="background-color: black;">
							Login
						</button>
					</div>
					
					{% comment %} <div class="text-center p-t-46 p-b-20">
						<span class="txt2">
							or sign up using
						</span>
					</div>

					<div class="login100-form-social flex-c-m">
						<a href="#" class="login100-form-social-item flex-c-m bg1 m-r-5">
							<i class="fa fa-facebook-f" aria-hidden="true"></i>
						</a>

						<a href="#" class="login100-form-social-item flex-c-m bg2 m-r-5">
							<i class="fa fa-twitter" aria-hidden="true"></i>
						</a>
					</div> {% endcomment %}
				</form>
                {{Error}}
				<div class="login100-more" style="background-image: url('{% static 'Login/images/bg-01.jpg' %}');">
				</div>
			</div>
		</div>
	</div>
	
	

	
	
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'Login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Login/js/main.js' %}"></script>

</body>
</html>

Guest/templates/Guest/NewAgency.html
{% extends 'Guest/Head.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <br><br><br><br>
    <div id="tab">
        <br><br><center><h2>New Agency</h2></center><br><br>
    
    <form action="" method="post" enctype="multipart/form-data" id="UserForm">
        {% csrf_token %}
        <table align="center" border="2">
            <tr>
                <td>Name</td>
                <td><input type="text" name="txt_name" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><input type="email" name="txt_email" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>CrimeType</td>
                <td><select name="sel_crimetype">
                    <option value="">----select----</option>
                    {% for i in CT %}
                    <option value="{{i.id}}">{{i}}</option>
                    {% endfor %}
                </select></td>
            </tr>
            <tr>
                <td>Logo</td>
                <td><input type="file" name="logo"></td>
            </tr>
            <tr>
                <td>Proof</td>
                <td><input type="file" name="proof"></td>
            </tr>
            <tr>
                <td>Password</td>
                <td><input type="password" name="txt_pass"></td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <input type="submit" name="save" value="Submit">
                    <input type="reset" name="cancel" value="Cancel">
                </td>
            </tr>
        </table>
    </form>
    </div>
</body>
</html>
<br><br>
{% endblock content %}

Guest/templates/Guest/NewUser.html
{% extends 'Guest/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <br><br><br><br>
    <div id="tab">
        <br><br><center><h2>New User</h2></center><br><br>
    <form action="" method="post" id="UserForm" data-places-url="{% url 'guest:Ajax_Place' %}">
        {% csrf_token %}
        <table align="center" border="2">
            <tr>
                <td>Name</td>
                <td><input type="text" name="txt_name" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Contact</td>
                <td><input type="text" name="txt_cntct" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Email</td>
                <td><input type="email" name="txt_email" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Address</td>
                <td><textarea name="txt_address" cols="30" rows="10" required="" autocomplete="off"></textarea></td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>
                    <input type="radio" name="gender" value="M" required="">Male
                    <input type="radio" name="gender" value="F" required="">Female
                    <input type="radio" name="gender" value="O" required="">Others
                </td>
            </tr>
            <tr>
                <td>District</td>
                <td><select name="sel_dis" id="district" required="">
                    <option value="">----select----</option>
                    {% for i in Dis %}
                    <option value="{{i.id}}">{{i}}</option>
                    {% endfor %}
                </select></td>
            </tr>
            <tr>
                <td>Place</td>
                <td><select name="sel_plc" id="place" required="">
                    <option value="">----select----</option>
                </select></td>
            </tr>
            <tr>
                <td>Password</td>
                <td><input type="password" name="txt_pwd" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td>Confirm Password</td>
                <td><input type="password" name="txt_cpwd" required="" autocomplete="off"></td>
            </tr>
            <tr>
                <td colspan="2" align="center"><input type="submit" name="save" value="Submit">
                    <input type="reset" name="cancel" value="Cancel"></td>
            </tr>
        </table>
    </form>
    </div>
</body>
</html>
<br><br>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $("#district").change(function () {
            var did = $(this).val();
            var ur = $("#UserForm").attr("data-places-url");
            $.ajax({
                url: ur,
                data: { district: did, },
                success: function (data) {
                    $("#place").html(data);
                },
            });
        });
    </script>

    {% endblock content %}