Guest/urls.py
from django.urls import path
from Guest import views
app_name='guest'

urlpatterns = [
    path('home/',views.home,name="Home"),
    path('newuser/',views.newuser,name="Newuser"),
    path('ajax_place/',views.ajaxplace,name="Ajax_Place"),
    path('login/',views.login,name="Login"),
    path('newagency/',views.newagency,name="NewAgency"),
]

MissionSeeker/urls.py
from django.contrib import admin
from django.urls import path,include

from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('WebAdmin/',include('Admin.urls')),
    path('agency/',include('Agency.urls')),
    path('user/',include('User.urls')),
    path('guest/',include('Guest.urls')),
    path('',views.home,name="Home"),
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views
app_name='user'

urlpatterns = [
    path('homeuser/',views.userhome,name="User-Home"),
    path('userprofile/',views.uprofile,name="User_Profile"),
    path('editprof/<int:euid>',views.ueditprof,name="U_EditProfile"),
    path('changepass/<int:cuid>',views.uchangepass,name="U_ChangePwd"),
    path('ucomplaint/',views.UComplaint,name="UComplaint"),
    path('search_agency/',views.SearchAg,name="SearchAgency"),
    path('get_agency/',views.getAgency,name="GetAgency"),
    path('crime/<int:aid>',views.crime,name="Crime"),
    path('Key/<int:cid>', views.keyverification, name="User_Key"),
    path('Chat/', views.chatuser, name="Chat-user"),
    path('loadchat/', views.loadchatuser, name="load-chat"),
]

User/models.py
from django.db import models
from Guest.models import *

# Create your models here.

class Complaint(models.Model):
    content=models.TextField(null=True)
    reply=models.TextField(null=True)
    user=models.ForeignKey(NewUser,on_delete=models.SET_NULL,null=True)
    agency=models.ForeignKey(NewAgency,on_delete=models.SET_NULL,null=True)
    c_status=models.IntegerField(default=0)
    
    
class Crime(models.Model):
    crime_description=models.TextField(null=True)
    crimetype=models.ForeignKey(CrimeType,on_delete=models.CASCADE)
    user=models.ForeignKey(NewUser,on_delete=models.SET_NULL,null=True)
    agency=models.ForeignKey(NewAgency,on_delete=models.SET_NULL,null=True)
    c_vsts=models.IntegerField(default=0)
    
class Chat(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    from_user = models.ForeignKey(
        NewUser, on_delete=models.SET_NULL, default=False, null=True, related_name="from_user")
    to_user = models.ForeignKey(
        NewUser, on_delete=models.SET_NULL, default=False, null=True, related_name="to_user")
    from_agency = models.ForeignKey(
        NewAgency, on_delete=models.SET_NULL, default=False, null=True, related_name="from_agency")
    to_agency = models.ForeignKey(
        NewAgency, on_delete=models.SET_NULL, default=False, null=True, related_name="to_agency")
    content = models.BinaryField(max_length=10000)
    

User/views.py
from django.shortcuts import redirect, render
from cryptography.fernet import Fernet
from Guest.models import *
from User.models import *

# Create your views here.

def userhome(request):
    user=NewUser.objects.get(id=request.session['uid'])
    return render(request,"User/User_Home.html",{'U':user})

def uprofile(request):
    profile=NewUser.objects.get(id=request.session['uid'])
    return render(request,"User/U_Profile.html",{'Profile':profile})

def ueditprof(request,euid):
    if "uid" in request.session:
        selU=NewUser.objects.get(id=euid)
        if request.method=="POST":
            selU.name=request.POST.get('txtname')
            selU.contact=request.POST.get('txtcntct')
            selU.email=request.POST.get('txtemail')
            selU.address=request.POST.get('txtaddress')
            selU.save()
            return redirect('user:User_Profile')
        else:
            return render(request,"User/U_EditProfile.html",{'EP':selU})
    else:
        return redirect('guest:Login')
    
def uchangepass(request,cuid):
    change=NewUser.objects.get(id=cuid)
    pwd=change.password
    if request.method=="POST":
        old=request.POST.get('cpwd')
        if old!=pwd:
            error="Password Not Correct"
            return render(request,"User/U_ChangePassword.html",{'Error':error})
        else:
            new=request.POST.get('npwd')
            change=NewUser.objects.get(id=cuid)
            change.password=new
            change.save()
            return redirect('guest:Login')
    else:
        return render(request,"User/U_ChangePassword.html")

def UComplaint(request):
    if request.method=="POST":
        User=NewUser.objects.get(id=request.session['uid'])
        Complaint.objects.create(content=request.POST.get('txtcontent'),user=User)
        cmp=Complaint.objects.filter(user=request.session['uid'])
        return render(request,"User/U_Complaint.html",{'CMP':cmp})
    else:
        cmp=Complaint.objects.filter(user=request.session['uid'])
        return render(request,"User/U_Complaint.html",{'CMP':cmp})


def SearchAg(request):
    dist=District.objects.all()
    ctype=CrimeType.objects.all()
    ag=NewAgency.objects.all()
    return render(request,"User/Search_Agency.html",{'Dis':dist,'CT':ctype,'Ag':ag})

def getAgency(request):
    ctype=request.GET.get('crimetype')
    ag=NewAgency.objects.filter(crimetype=ctype)
    return render(request,"User/GetAgency.html",{'AG':ag})
 
 
def crime(request,aid):
    agencyid=NewAgency.objects.get(id=aid)
    ctype=CrimeType.objects.all()
    if request.method=="POST":
        userid=NewUser.objects.get(id=request.session['uid'])         
        ctid=request.POST.get('sel_crimetype')
        ct=CrimeType.objects.get(id=ctid)
        Crime.objects.create(crime_description=request.POST.get('txtdes'),crimetype=ct,agency=agencyid,user=userid)
        cm=Crime.objects.filter(user=request.session['uid'],agency=agencyid)
        return render(request,"User/Crime.html",{'CT':ctype,'CM':cm})
    else:
        cm=Crime.objects.filter(user=request.session['uid'],agency=agencyid)
        return render(request,"User/Crime.html",{'CT':ctype,'CM':cm})
    
def keyverification(request,cid):
    request.session['did']=cid
    
    userid=NewUser.objects.get(id=request.session['uid'])
    K=userid.key
    print(K)
        
    if request.method=="POST":
        Key=request.POST.get('en_key')
        Key = Key.encode()
        if Key==K:
            return redirect('user:Chat-user')
        else:
            error="Key Incorrect!!"
            return render(request,"User/KeyVerification.html",{'ERROR':error})
    else:
        return render(request,"User/KeyVerification.html")
        
    
def chatuser(request):
    chatobj = Crime.objects.get(id=request.session["did"])
    if request.method == "POST":
       
        cied = request.POST.get("cid")
        # print(cied)
        ciedobj = NewAgency.objects.get(id=cied)
        key=ciedobj.keys
        a=Fernet(key)

        '''key=bytes(key,'utf-8')
        print(key)
        with open("pass.key", "wb") as key_file:
            key_file.write(key)
        key=call_key()
        
        key=key.decode('utf-8')
        key=base64.urlsafe_b64encode(bytes(key,'utf-8'))
        print(key)
        a=Fernet(key)'''
        sobj = NewUser.objects.get(id=request.session["uid"])
        content = request.POST.get("msg")
        slog=content.encode()
        coded_slog=a.encrypt(slog)
        print("Encrypted")
        print(coded_slog)
        decoded_slog=a.decrypt(coded_slog)
        print("Decrypted")
        
        cont=decoded_slog.decode()
        print(cont)
        # print(cied)
        # print(content)
        Chat.objects.create(
            from_user=sobj, to_agency=ciedobj, content=coded_slog, from_agency=None, to_user=None)
        return render(request, 'User/Chat.html', {"chatobj": chatobj})
    else:
        return render(request, 'User/Chat.html', {"chatobj": chatobj})


def loadchatuser(request):
    cid = request.GET.get("cid")
    request.session["cid"] = cid

    cid1 = request.session["cid"]
    # print(cid1)

    # print(cid)
    shopobj = NewAgency.objects.get(id=cid)
    key=shopobj.keys
    a=Fernet(key)
    # print(userobj)
    sid = request.session["uid"]
    # print(sid)
    suserobj = NewUser.objects.get(id=request.session["uid"])
    key1=suserobj.key
    b=Fernet(key1)
    # chatobj1 = Chat.objects.filter(Q(to_user=suserobj) | Q(
    #     from_user=suserobj), Q(to_shop=shopobj) | Q(from_shop=shopobj))
    # print(chatobj1)  # send message

    # print(chatobj2)  # recived msg
    chatobj = Chat.objects.raw(
        "select * from User_chat c inner join Guest_newuser u on (u.id=c.from_user_id) or (u.id=c.to_user_id) WHERE  c.from_agency_id=%s or c.to_agency_id=%s order by c.date", params=[(cid1), (cid1)])
    

    leh=(len(chatobj))
    #message=[0 for i in range(0,leh)]
    for i in range(0,leh):
        csid=int(cid)
        if chatobj[i].from_user_id==sid and chatobj[i].to_agency_id==csid:
            chatobj[i].content=a.decrypt(chatobj[i].content).decode()
        elif chatobj[i].to_user_id==sid and chatobj[i].from_agency_id==csid:
            chatobj[i].content=b.decrypt(chatobj[i].content).decode()
    #print(message)
        

    return render(request, 'User/Load.html', {"obj":chatobj, "sid": sid, "shop": shopobj, "userobj": suserobj})

     

def call_key():
    return open("pass.key", "rb").read()

User/templates/User/Chat.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Chat</title>
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}" />
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/core.css' %}">

</head>
<!-- select query -->

<body>

    <!-- Pageloader -->
    <div class="pageloader"></div>
    <div class="infraloader is-active"></div>

    <div class="chat-wrapper is-standalone">
        <div class="chat-inner">

            <!-- Chat top navigation -->
            <div class="chat-nav">
                <div class="nav-start">
                    <div class="recipient-block">
                        <div class="avatar-container">
                            <img class="user-avatar" src="{% static 'assets/img/chat.png' %}" alt="">
                        </div>
                        <div class="username">
                            <span>
                                {{ chatobj.agency.ag_name }}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="nav-end">

                    <a href="" class="chat-nav-item is-icon is-hidden-mobile">
                        <i data-feather="home"></i>
                    </a>
                    {% comment %} {% url 'user:User-Home' chatobj.id %} {% endcomment %}
                </div>
            </div>

            <form method="post">
                {% csrf_token %}
                <!-- Chat body -->
                <div id="chat-body" class="chat-body">
                    <!-- Conversation -->
                    <div id="conversation" class="chat-body-inner has-slimscroll">

                    </div>
                    <!-- Compose message area -->
                    <div class="chat-action">
                        <div class="chat-action-inner">
                            <div class="control" style="text-align: center">
                                <input type="hidden" name="cid" id="cid" value="{{chatobj.agency.id}}" />
                                <textarea class="textarea comment-textarea" id="msg" name="msg" rows="2"></textarea>
                                <input type="submit" value="Send" name="btn_send" id="btn_send" style="border: none;background-color: #5082c3;border-radius: 15px 10px; color: white;
                                       margin: 10px; margin-bottom: 30px ; width: 30%; height: 25px">

                            </div>
                        </div>
                    </div>

                </div>
            </form>

        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script>

        function sendChat() {

            var chat = document.getElementById("msg").value;
            var cid = document.getElementById("cid").value;
            if (chat.length <= 35) {
                $.ajax({
                    url: "/user/loadchat/",
                    data: "chat=" + chat + "&cid=" + cid,
                    success: function (result) {


                        document.getElementById("msg").value = "";

                        $('#conversation').animate({ scrollTop: $('#conversation')[0].scrollHeight });


                    }
                });
            }
            else {
                alert("Character Length less Than 35 Allowed");
                document.getElementById("msg").value = "";

                $('#conversation').animate({ scrollTop: $('#conversation')[0].scrollHeight });
            }

        }
        $(document).ready(function () {
            setInterval(function () {
                var cid = document.getElementById("cid").value;
                console.log(cid);
                $("#conversation").load('/user/loadchat/?cid=' + cid)
            }, 50);
        });

    </script>
    <!-- Concatenated js plugins and jQuery -->
    <script src="{% static 'assets/js/app.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'assets/data/tipuedrop_content.js' %}"></script>

    <!-- Core js -->
    <script src="{% static 'assets/js/global.js' %}"></script>

    <!-- Navigation options js -->
    <script src="{% static 'assets/js/navbar-v1.js' %}"></script>
    <script src="{% static 'assets/js/navbar-v2.js' %}"></script>
    <script src="{% static 'assets/js/navbar-mobile.js' %}"></script>
    <script src="{% static 'assets/js/navbar-options.js' %}"></script>
    <script src="{% static 'assets/js/sidebar-v1.js' %}"></script>

    <!-- Core instance js -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/chat.js' %}"></script>
    <script src="{% static 'assets/js/touch.js' %}"></script>
    <script src="{% static 'assets/js/tour.js' %}"></script>

    <!-- Components js -->
    <script src="{% static 'assets/js/explorer.js' %}"></script>
    <script src="{% static 'assets/js/widgets.js' %}"></script>
    <script src="{% static 'assets/js/modal-uploader.js' %}"></script>
    <script src="{% static 'assets/js/popovers-users.js' %}"></script>
    <script src="{% static 'assets/js/popovers-pages.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.js' %}"></script>




</body>

</html>

User/templates/User/Crime.html
{% extends 'User/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%  block content %}
    <div id="tab">
        <br><br><center><h2>Crime</h2></center><br><br>
        {{ERROR}}
    <form action="" method="post">
        {% csrf_token %}
        <table align="center" border="2">

            <tr>
                <td>Crime Type</td>
                <td><select name="sel_crimetype" id="crimetype">
                    <option value="">----select----</option>
                    
                    {% for i in CT %}
                        <option value="{{i.id}}">{{i}}</option>
                    {% endfor %}
                        
                </select>
                </td>
            </tr>
            <tr>
                <td>Description</td>
                <td><textarea name="txtdes" id="" cols="30" rows="10"></textarea></td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" name="save" value="SEND">
                    <input type="reset" name="cancel" value="CANCEL">
                </td>
            </tr>
            <tr>
                <td><input type="hidden" name="en_key" id="key"></td>
            </tr>
        </table>
        <br><br><br>
        <table border="1" align="center">
            <tr>
                <th>Crime Type</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
            
            {% for i in CM %}
            <tr>
                <td>{{i.crimetype}}</td>
                <td>{{i.crime_description}}</td>
                <td>
                    {% if i.c_vsts == 0 %}
                    <p>Pending..</p>
                    {% elif i.c_vsts == 1 %}
                    <a href="{% url 'user:User_Key' i.id %}">Chat Now</a>
                    {% else %}
                    <p>Rejected..</p>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
                
        </table>
    </form>
    </div>
</body>
</html>
<br><br>

<script>
    function myFunction() {
      let person = prompt("Please enter your Key", "");
      if (person != null) {
        document.getElementById("key").innerHTML =
        "Hello " + person + "! How are you today?";
      }
    }
    </script>

{% endblock content %}

User/templates/User/GetAgency.html
{% comment %} {% extends 'User/Head.html' %}
{% load static %}
{%  block content %} {% endcomment %}
<table align="center" cellpadding="50" style="border-collapse:collapse">    
    <tr>
        {%for i in AG %}
        <td>
            <div style="text-align:center;border:1px solid black;margin:22px;padding:20px">
                <p><image src={{i.ag_logo.url}} width="100px" height="100px"></p>
                <p>{{i.ag_name}}</p>
                <p>{{i.ag_email}}</p>
                <p>{{i.crimetype}}</p>
                <p><a href="{% url 'user:Crime' i.id %}">Request</a></p>
            </div>
        <td>
            {% if forloop.counter|divisibleby:4 %}
    </tr>
    <tr>
            {% endif %}
            
        {%endfor%}
</table><br><br>
{% comment %} {% endblock content %} {% endcomment %}

User/templates/User/Head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<!-- For IE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<!-- For Resposive Device -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>MISSION SEEKER</title>

		<!-- Favicon -->
		<link rel="icon" type="image/png" sizes="56x56" href="{% static 'Main/images/fav-icon/icon.png' %}">


		<!-- Main style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'Main/css/style.css' %}">
		<link rel="stylesheet" href="{% static 'Form/form.css' %}">
		<!-- responsive style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'Main/css/responsive.css' %}">


		<!-- Fix Internet Explorer ______________________________________-->

		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
			<script src="vendor/html5shiv.js"></script>
			<script src="vendor/respond.js"></script>
		<![endif]-->
			
	</head>

	<body>
		<div class="main-page-wrapper">



			<!-- 
			=============================================
				Theme Header
			============================================== 
			-->
			<header class="theme-main-header" style="background-color:black;">
				<div class="container">
					<a href="index.html" class="logo float-left tran4s"><img src="#" alt=""></a>
					
					<!-- ========================= Theme Feature Page Menu ======================= -->
					<nav class="navbar float-right theme-main-menu one-page-menu">
					   <!-- Brand and toggle get grouped for better mobile display -->
					   <div class="navbar-header">
					     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
					       <span class="sr-only">Toggle navigation</span>
					       Menu
					       <i class="fa fa-bars" aria-hidden="true"></i>
					     </button>
					   </div>
					   <!-- Collect the nav links, forms, and other content for toggling -->
					   <div class="collapse navbar-collapse" id="navbar-collapse-1">
					     <ul class="nav navbar-nav">
					       	<li class="active"><a href="{% url 'user:User-Home' %}">Home</a></li>
							<li><a href="{% url 'user:User_Profile' %}">Profile</a></li>
							<li><a href="{% url 'user:UComplaint' %}">Complaint</a></li>
							<li><a href="{% url 'user:SearchAgency' %}">Search Agency</a></li>
							<li><a href="{% url 'guest:Login' %}">LogOut</a></li>
							{% comment %} <li class="dropdown-holder"><a href="#blog-section">BLOG</a>
								<ul class="sub-menu">
					       			<li><a href="blog-details.html" class="tran3s">Blog Details</a></li>
					       		</ul>
							</li>
							<li><a href="#contact-section">CONTACT</a></li> {% endcomment %}
					     </ul>
					   </div><!-- /.navbar-collapse -->
					</nav> <!-- /.theme-feature-menu -->
				</div>
			</header> <!-- /.theme-main-header -->


			<!--
			=====================================================
				Theme Main SLider
			=====================================================
			-->

			
			
			
									{% block content %}

                                    {% endblock content %}

                                

                    <!--
			=====================================================
				Footer
			=====================================================
			-->
		
			<footer>
				<div class="container">
					<a href="index.html" class="logo"><img src="" alt=""></a>

					<ul>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-flickr" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
					</ul>
					<p>Copyright @2018 All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
				</div>
			</footer>




			<!-- =============================================
				Loading Transition
			============================================== -->
			<div id="loader-wrapper">
				<div id="preloader_1">
	                <span></span>
	                <span></span>
	                <span></span>
	                <span></span>
	                <span></span>
	            </div>
			</div>

			
	        <!-- Scroll Top Button -->
			<button class="scroll-top tran3s p-color-bg">
				<i class="fa fa-long-arrow-up" aria-hidden="true"></i>
			</button>




		<!-- Js File_________________________________ -->

		<!-- j Query -->
		<script type="text/javascript" src="{% static 'Main/vendor/jquery.2.2.3.min.js' %}"></script>

		<!-- Bootstrap JS -->
		<script type="text/javascript" src="{% static 'Main/vendor/bootstrap/bootstrap.min.js' %}"></script>

		<!-- Vendor js _________ -->
		
		<!-- revolution -->
		<script src="{% static 'Main/vendor/revolution/jquery.themepunch.tools.min.js' %}"></script>
		<script src="{% static 'Main/vendor/revolution/jquery.themepunch.revolution.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.slideanims.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.layeranimation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.navigation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.kenburn.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.actions.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.video.min.js' %}"></script>

		<!-- Google map js -->
		<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZ8VrXgGZ3QSC-0XubNhuB2uKKCwqVaD0&callback=goMap" type="text/javascript"></script> <!-- Gmap Helper -->
		<script src="{% static 'Main/vendor/gmaps.min.js' %}"></script>
		<!-- owl.carousel -->
		<script type="text/javascript" src="{% static 'Main/vendor/owl-carousel/owl.carousel.min.js' %}"></script>
		<!-- mixitUp -->
		<script type="text/javascript" src="vendor/jquery.mixitup.min.js' %}"></script>
		<!-- Progress Bar js -->
		<script type="text/javascript" src="vendor/skills-master/jquery.skills.js' %}"></script>
		<!-- Validation -->
		<script type="text/javascript" src="vendor/contact-form/validate.js' %}"></script>
		<script type="text/javascript" src="vendor/contact-form/jquery.form.js' %}"></script>


		<!-- Theme js -->
		<script type="text/javascript" src="{% static 'Main/js/theme.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/js/map-script.js' %}"></script>

		</div> <!-- /.main-page-wrapper -->
	</body>
</html>

User/templates/User/KeyVerification.html
{% extends 'User/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <br><br><br><br><br><br>
    <br><br><center><h2>Key Verification</h2></center><br><br> 
    <form action="" method="post">
        {% csrf_token %}
        <table border="1" align="center">
            <tr>
                <td><input type="text" name="en_key" id="key"></td>
            </tr>
            <tr>
                <td colspan="2" align="center"><input type="submit" name="check" value="Check"></td>
            </tr>
        </table>
    </form>
    {{ERROR}}
</body>
</html>

<br><br><br><br><br><br>
{% endblock content %}

User/templates/User/U_Profile.html
{% extends 'User/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User_Profile</title>
</head>
<body>
    {%  block content %}
    <br><br><br><br>
    <div id="tab">
        <br><br><center><h2>Profile</h2></center><br><br>
    <form action="" method="post">
        <table border="3" align="center">
            <tr>
                <td>Name</td>
                <td>{{Profile.name}}</td>
            </tr>
            <tr>
                <td>Contact</td>
                <td>{{Profile.contact}}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{Profile.email}}</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>{{Profile.address}}</td>
            </tr>
            <tr>
                <td>Gender</td>
                <td>{{Profile.gender}}</td>
            </tr>
            <tr>
                <td>Place</td>
                <td>{{Profile.place}}</td>
            </tr>
            <tr>
                <td><a href="{% url 'user:U_EditProfile' Profile.id %}">EditProfile</a></td>
                <td><a href="{% url 'user:U_ChangePwd' Profile.id %}">ChangePassword</a></td>
            </tr>
        </table>
    </form>
    </div>
</body>
</html>
<br><br>
{% endblock content %}