Agency/urls.py
from django.urls import path
from Agency import views
app_name='agency'

urlpatterns = [
    path('homeagency/',views.agencyhome,name="Agency-Home"),
    path('ag_profile/',views.ag_profile,name="Agency_Profile"),
    path('ag_editProf/<int:eagid>',views.ageditprof,name="AG_EditProfile"),
    path('ag_changepass/<int:cagid>',views.agchangepass,name="AG_ChangePwd"),
    path('crimevrf/',views.CrimeVrf,name="CrimeVerification"),
    path('acptcrime/',views.AcptCrime,name="AcceptedCrime"),
    path('rjctcrime/',views.RjctCrime,name="RejectedCrime"),
    path('agcmplnt/',views.AGCmplnt,name="AGComplaints"),  
    path('accpt_crime/<int:aid>',views.accept_crime,name="Accept_Crime"),
    path('rjct_crime/<int:rid>',views.reject_crime,name="Reject_Crime"),
    path('Key/<int:cid>', views.a_keyverification, name="Agency_Key"),
    path('Chat/', views.chat, name="Chat-agency"),
    path('loadchat/', views.loadchat, name="load-chat"),
]

Guest/urls.py
from django.urls import path
from Guest import views
app_name='guest'

urlpatterns = [
    path('home/',views.home,name="Home"),
    path('newuser/',views.newuser,name="Newuser"),
    path('ajax_place/',views.ajaxplace,name="Ajax_Place"),
    path('login/',views.login,name="Login"),
    path('newagency/',views.newagency,name="NewAgency"),
]

MissionSeeker/urls.py
from django.contrib import admin
from django.urls import path,include

from Guest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('WebAdmin/',include('Admin.urls')),
    path('agency/',include('Agency.urls')),
    path('user/',include('User.urls')),
    path('guest/',include('Guest.urls')),
    path('',views.home,name="Home"),
]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views
app_name='user'

urlpatterns = [
    path('homeuser/',views.userhome,name="User-Home"),
    path('userprofile/',views.uprofile,name="User_Profile"),
    path('editprof/<int:euid>',views.ueditprof,name="U_EditProfile"),
    path('changepass/<int:cuid>',views.uchangepass,name="U_ChangePwd"),
    path('ucomplaint/',views.UComplaint,name="UComplaint"),
    path('search_agency/',views.SearchAg,name="SearchAgency"),
    path('get_agency/',views.getAgency,name="GetAgency"),
    path('crime/<int:aid>',views.crime,name="Crime"),
    path('Key/<int:cid>', views.keyverification, name="User_Key"),
    path('Chat/', views.chatuser, name="Chat-user"),
    path('loadchat/', views.loadchatuser, name="load-chat"),
]

Agency/models.py
from django.db import models

# Create your models here.

Agency/views.py
from django.shortcuts import render,redirect
from cryptography.fernet import Fernet
from Guest.models import NewAgency
from User.models import *

# Create your views here.

def agencyhome(request):
    
    return render(request,"Agency/Agency_Home.html")

def ag_profile(request):
    profile=NewAgency.objects.get(id=request.session['agid'])
    return render(request,"Agency/AG_Profile.html",{'AP':profile})

def ageditprof(request,eagid):
    if "agid" in request.session:
        selAG=NewAgency.objects.get(id=eagid)
        if request.method=="POST":
            selAG.ag_name=request.POST.get('txtname')
            selAG.ag_email=request.POST.get('txtemail')
            selAG.save()
            return redirect('agency:Agency_Profile')
        else:
            return render(request,"Agency/AG_EditProfile.html",{'EP':selAG})
    else:
        return redirect('guest:Login')
    
def agchangepass(request,cagid):
    change=NewAgency.objects.get(id=cagid)
    pwd=change.ag_password
    if request.method=="POST":
        old=request.POST.get('cpwd')
        if old!=pwd:
            error="Password Not Correct"
            return render(request,"Agency/AG_ChangePassword.html",{'Error':error})
        else:
            new=request.POST.get('npwd')
            change=NewAgency.objects.get(id=cagid)
            change.ag_password=new
            change.save()
            return redirect('guest:Login')
    else:
        return render(request,"Agency/AG_ChangePassword.html")

def CrimeVrf(request):
    cv=Crime.objects.filter(agency=request.session['agid'])
    return render(request,"Agency/Crime_verification.html",{'C':cv})


def a_keyverification(request,cid):
    request.session['aid']=cid
    
    agnid=NewAgency.objects.get(id=request.session['agid'])
    K=agnid.keys
    print(K)
        
    if request.method=="POST":
        Key=request.POST.get('en_key')
        Key = Key.encode()
        if Key==K:
            return redirect('agency:Chat-agency')
        else:
            error="Key Incorrect!!"
            return render(request,"Agency/KeyVerification.html",{'ERROR':error})
    else:
        return render(request,"Agency/KeyVerification.html")
    

def accept_crime(request,aid):
    ac=Crime.objects.get(id=aid)
    ac.c_vsts=1
    ac.save()
    return redirect('agency:CrimeVerification')


def reject_crime(request,rid):
    rc=Crime.objects.get(id=rid)
    rc.c_vsts=2
    rc.save()
    return redirect('agency:CrimeVerification')

def AcptCrime(request):
    cv=Crime.objects.filter(c_vsts=1,agency=request.session['agid'])
    return render(request,"Agency/Accepted_Crime.html",{'C':cv})

def RjctCrime(request):
    cv=Crime.objects.filter(c_vsts=2,agency=request.session['agid'])
    return render(request,"Agency/Rejected_crime.html",{'C':cv})

def AGCmplnt(request):
    if request.method=="POST":
        Agency=NewAgency.objects.get(id=request.session['agid'])
        Complaint.objects.create(content=request.POST.get('txtcontent'),agency=Agency)
        cmp=Complaint.objects.filter(agency=request.session['agid'])
        return render(request,"Agency/AG_Complaint.html",{'CMP':cmp})
    else:
        cmp=Complaint.objects.filter(user=request.session['agid'])
        return render(request,"Agency/AG_Complaint.html",{'CMP':cmp})
    
    
def chat(request):
    chatobj = Crime.objects.get(id=request.session["aid"])
    if request.method == "POST":
        cied = request.POST.get("cid")
        # print(cied)
        ciedobj = NewUser.objects.get(id=cied)
        key=ciedobj.key
        a=Fernet(key)
        sobj = NewAgency.objects.get(id=request.session["agid"])
        content = request.POST.get("msg")
        slog=content.encode()
        encrypted=a.encrypt(slog)
        # print(cied)
        print(content)
        Chat.objects.create(
            from_agency=sobj, to_user=ciedobj, content=encrypted, from_user=None, to_agency=None)
        return render(request, 'Agency/Chat.html', {"chatobj": chatobj})
    else:
        return render(request, 'Agency/Chat.html', {"chatobj": chatobj})


def loadchat(request):
    cid = request.GET.get("cid")
    request.session["cid"] = cid

    cid1 = request.session["cid"]
    # print(cid1)

    # print(cid)
    shopobj = NewUser.objects.get(id=cid)
    key1=shopobj.key
    
    b=Fernet(key1)
    
    # print(userobj)
    sid = request.session["agid"]
    
    # print(sid)
    suserobj = NewAgency.objects.get(id=request.session["agid"])
    key=suserobj.keys
    a=Fernet(key)

    chatobj = Chat.objects.raw(
        "select * from User_chat c inner join Guest_newagency u on (u.id=c.from_agency_id) or (u.id=c.to_agency_id) WHERE  c.from_user_id=%s or c.to_user_id=%s order by c.date", params=[(cid1), (cid1)])
    
    leh=(len(chatobj))
    message=[0 for i in range(0,leh)]
    
    for i in range(0,leh):
        csid=int(cid)
        if chatobj[i].from_user_id==csid and chatobj[i].to_agency_id==sid:
            chatobj[i].content=a.decrypt(chatobj[i].content).decode()
        elif chatobj[i].to_user_id==csid and chatobj[i].from_agency_id==sid:
            chatobj[i].content=b.decrypt(chatobj[i].content).decode()
    # print(message)   
    lk=[0 for i in range(0,leh)]  
    for i in range(0,leh):
        lk[i]=i
    return render(request, 'Agency/Load.html', {"obj": chatobj, "sid": sid, "shop": shopobj, "userobj": suserobj,'content':message,'len':lk})

Agency/templates/Agency/AG_ChangePassword.html
{% extends 'agency/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChangePassword</title>
</head>
<body>
    {%  block content %}
    <div id="tab">
        <br><br><br><br>
        <br><br><center><h2>Change Password </h2></center><br><br>
    <form action="" method="post">
        {% csrf_token %}
        <table border="2" align="center">
         <tr>
            <td>Current Password</td>
            <td><input type="password" name="cpwd" id="" placeholder="Enter Current Password" required="" autocomplete="off"></td>
         </tr>
         <tr>
            <td>New Password</td>
            <td><input type="password" name="npwd" id="" placeholder="Enter New Password" required="" autocomplete="off"></td>
         </tr>
         <tr>
            <td>Confirm Password</td>
            <td><input type="password" name="cfpwd" id="" placeholder="Re-Enter New Password" onblur="return checkpwd(this,npwd)" required="" autocomplete="off"></td>
         </tr>
         <tr>
            <td colspan="2" align="center"><input type="submit" name="save" value="Change">
                <input type="reset" name="cancel" value="Cancel"></td>
            </tr>
        </table>
    </form>
    </div>
    {{Error}}
</body>
</html>
<br><br>

<script>
    function checkpwd(confirm, passwd) {
        if (confirm.value != passwd.value) {
            alert("Password Mismatch")
            return false
        }
        else {
            return true
        }
    }
</script>
{% endblock content %}

Agency/templates/Agency/AG_Profile.html
{% extends 'agency/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User_Profile</title>
</head>

<body>
    {%  block content %}
    <br><br><br><br>
    <div id="tab">
        <br><br><center><h2>Profile</h2></center><br><br>
    <form action="" method="post">
        <table border="3" align="center">
            <tr>
                <td colspan="2" align="center"><img src="{{AP.ag_logo.url}}" width="120px" height="120px"></td>
            </tr>
            <tr>
                <td>Name</td>
                <td>{{AP.ag_name}}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{AP.ag_email}}</td>
            </tr>
            <tr>
                <td>Proof</td>
                <td>{{AP.ag_proof}}</td>
            </tr>
            <tr>
                <td><a href="{% url 'agency:AG_EditProfile' AP.id %}">EditProfile</a></td>
                <td><a href="{% url 'agency:AG_ChangePwd' AP.id %}">ChangePassword</a></td>
            </tr>
        </table>
    </form>
    </div>
</body>

</html>
<br><br>
{% endblock content %}

Agency/templates/Agency/Accepted_Crime.html
{% extends 'agency/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%  block content %}
    <br><br><br><br>
    <div id="tab">
        <br><br><center><h2>Accepted Crime</h2></center><br><br>
    <form action="" method="post">
        <table align="center" border="2">
            <tr>
                <th>User Name</th>
                <th>Crime Type</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
            {% for i in C %}
            <tr>
                <td>{{i.user.name}}</td>
                <td>{{i.crimetype}}</td>
                <td>{{i.crime_description}}</td>
                <td><a href="{% url 'agency:Reject_Crime' i.id %}">Reject</a></td>
            </tr>
            {% endfor %}
        </table>
    </form>
    </div>
</body>
</html>
<br><br>
{% endblock content %}

Agency/templates/Agency/Chat.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Chat</title>
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}" />
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet">
    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/core.css' %}">

</head>
<!-- select query -->

<body>

    <!-- Pageloader -->
    <div class="pageloader"></div>
    <div class="infraloader is-active"></div>

    <div class="chat-wrapper is-standalone">
        <div class="chat-inner">

            <!-- Chat top navigation -->
            <div class="chat-nav">
                <div class="nav-start">
                    <div class="recipient-block">
                        <div class="avatar-container">
                            <img class="user-avatar" src="{% static 'assets/img/chat.png' %}" alt="">
                        </div>
                        <div class="username">
                            <span>
                                {{ chatobj.user.name }}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="nav-end">

                    <a href="{% url 'agency:Agency-Home' %}" class="chat-nav-item is-icon is-hidden-mobile">
                        <i data-feather="home"></i>
                    </a>

                </div>
            </div>

            <form method="post">
                {% csrf_token %}
                <!-- Chat body -->
                <div id="chat-body" class="chat-body">
                    <!-- Conversation -->
                    <div id="conversation" class="chat-body-inner has-slimscroll">

                    </div>
                    <!-- Compose message area -->
                    <div class="chat-action">
                        <div class="chat-action-inner">
                            <div class="control" style="text-align: center">
                                <input type="hidden" name="cid" id="cid" value="{{chatobj.user.id}}" />
                                <textarea class="textarea comment-textarea" id="msg" name="msg" rows="2"></textarea>
                                <input type="submit" value="Send" name="btn_send" id="btn_send" style="border: none;background-color: #5082c3;border-radius: 15px 10px; color: white;
                                       margin: 10px; margin-bottom: 30px ; width: 30%; height: 25px">

                            </div>
                        </div>
                    </div>

                </div>
            </form>

        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script>

        function sendChat() {

            var chat = document.getElementById("msg").value;
            var cid = document.getElementById("cid").value;
            if (chat.length <= 35) {
                $.ajax({
                    url: "/agency/loadchat/",
                    data: "chat=" + chat + "&cid=" + cid,
                    success: function (result) {


                        document.getElementById("msg").value = "";

                        $('#conversation').animate({ scrollTop: $('#conversation')[0].scrollHeight });


                    }
                });
            }
            else {
                alert("Character Length less Than 35 Allowed");
                document.getElementById("msg").value = "";

                $('#conversation').animate({ scrollTop: $('#conversation')[0].scrollHeight });
            }

        }
        $(document).ready(function () {
            setInterval(function () {
                var cid = document.getElementById("cid").value;
                console.log(cid);
                $("#conversation").load('/agency/loadchat/?cid=' + cid)
            }, 50);
        });

    </script>
    <!-- Concatenated js plugins and jQuery -->
    <script src="{% static 'assets/js/app.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'assets/data/tipuedrop_content.js' %}"></script>

    <!-- Core js -->
    <script src="{% static 'assets/js/global.js' %}"></script>

    <!-- Navigation options js -->
    <script src="{% static 'assets/js/navbar-v1.js' %}"></script>
    <script src="{% static 'assets/js/navbar-v2.js' %}"></script>
    <script src="{% static 'assets/js/navbar-mobile.js' %}"></script>
    <script src="{% static 'assets/js/navbar-options.js' %}"></script>
    <script src="{% static 'assets/js/sidebar-v1.js' %}"></script>

    <!-- Core instance js -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/chat.js' %}"></script>
    <script src="{% static 'assets/js/touch.js' %}"></script>
    <script src="{% static 'assets/js/tour.js' %}"></script>

    <!-- Components js -->
    <script src="{% static 'assets/js/explorer.js' %}"></script>
    <script src="{% static 'assets/js/widgets.js' %}"></script>
    <script src="{% static 'assets/js/modal-uploader.js' %}"></script>
    <script src="{% static 'assets/js/popovers-users.js' %}"></script>
    <script src="{% static 'assets/js/popovers-pages.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.js' %}"></script>




</body>

</html>

Agency/templates/Agency/Crime_verification.html
{% extends 'agency/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%  block content %}
    <br><br><br><br>
    <div id="tab">
        <br><br><center><h2>Crime Verification</h2></center><br><br>
    <form action="" method="post">
        <table align="center" border="2">
            <tr>
                <th>User Name</th>
                <th>Crime Type</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
            
            {% for i in C %}
            <tr>
                <td>{{i.user.name}}</td>
                <td>{{i.crimetype}}</td>
                <td>{{i.crime_description}}</td>
                <td>
                    {% if i.c_vsts == 0 %}
                    <a href="{% url 'agency:Accept_Crime' i.id %}">Accept</a> ||
                    <a href="{% url 'agency:Reject_Crime' i.id %}">Reject</a>
                    {% elif i.c_vsts == 1 %}
                    <a href="{% url 'agency:Agency_Key'  i.id %}">Chat Now</a>
                    {% else %}
                    <p>Rejected..</p>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
                
        </table>
    </form>
    </div>
</body>
</html>
<br><br>
{% endblock content %}

Agency/templates/Agency/Head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<!-- For IE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<!-- For Resposive Device -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>MISSION SEEKER</title>

		<!-- Favicon -->
		<link rel="icon" type="image/png" sizes="56x56" href="{% static 'Main/images/fav-icon/icon.png' %}">


		<!-- Main style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'Main/css/style.css' %}">
		<link rel="stylesheet" href="{% static 'Form/form.css' %}">
		<!-- responsive style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'Main/css/responsive.css' %}">


		<!-- Fix Internet Explorer ______________________________________-->

		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
			<script src="vendor/html5shiv.js"></script>
			<script src="vendor/respond.js"></script>
		<![endif]-->
			
	</head>

	<body>
		<div class="main-page-wrapper">



			<!-- 
			=============================================
				Theme Header
			============================================== 
			-->
			<header class="theme-main-header" style="background-color:black;">
				<div class="container">
					<a href="index.html" class="logo float-left tran4s"><img src="#" alt=""></a>
					
					<!-- ========================= Theme Feature Page Menu ======================= -->
					<nav class="navbar float-right theme-main-menu one-page-menu">
					   <!-- Brand and toggle get grouped for better mobile display -->
					   <div class="navbar-header">
					     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
					       <span class="sr-only">Toggle navigation</span>
					       Menu
					       <i class="fa fa-bars" aria-hidden="true"></i>
					     </button>
					   </div>
					   <!-- Collect the nav links, forms, and other content for toggling -->
					   <div class="collapse navbar-collapse" id="navbar-collapse-1">
						<ul class="nav navbar-nav">
							  <li class="active"><a href="{% url 'agency:Agency-Home' %}">Home</a></li>
						   <li><a href="{% url 'agency:Agency_Profile' %}">Profile</a></li>
						   <li><a href="{% url 'agency:CrimeVerification' %}">Crime Verification</a></li>
						   <li><a href="{% url 'agency:AcceptedCrime' %}">Accepted Crime </a></li>
						   <li><a href="{% url 'agency:RejectedCrime' %}">Rejected Crime</a></li>
						   <li><a href="{% url 'agency:AGComplaints' %}">Complaints</a></li>
						   <li><a href="{% url 'guest:Login' %}">LogOut</a></li>
						   {% comment %} <li class="dropdown-holder"><a href="#blog-section">BLOG</a>
							   <ul class="sub-menu">
									  <li><a href="blog-details.html" class="tran3s">Blog Details</a></li>
								  </ul>
						   </li>
						   <li><a href="#contact-section">CONTACT</a></li> {% endcomment %}
						</ul>
					  </div><!-- /.navbar-collapse -->
					</nav> <!-- /.theme-feature-menu -->
				</div>
			</header> <!-- /.theme-main-header -->


			<!--
			=====================================================
				Theme Main SLider
			=====================================================
			-->

			
			
			
									{% block content %}

                                    {% endblock content %}

                                

                    <!--
			=====================================================
				Footer
			=====================================================
			-->
		
			<footer>
				<div class="container">
					<a href="index.html" class="logo"><img src="" alt=""></a>

					<ul>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-flickr" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						<li><a href="#" class="tran3s round-border"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
					</ul>
					<p>Copyright @2018 All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
				</div>
			</footer>




			<!-- =============================================
				Loading Transition
			============================================== -->
			<div id="loader-wrapper">
				<div id="preloader_1">
	                <span></span>
	                <span></span>
	                <span></span>
	                <span></span>
	                <span></span>
	            </div>
			</div>

			
	        <!-- Scroll Top Button -->
			<button class="scroll-top tran3s p-color-bg">
				<i class="fa fa-long-arrow-up" aria-hidden="true"></i>
			</button>




		<!-- Js File_________________________________ -->

		<!-- j Query -->
		<script type="text/javascript" src="{% static 'Main/vendor/jquery.2.2.3.min.js' %}"></script>

		<!-- Bootstrap JS -->
		<script type="text/javascript" src="{% static 'Main/vendor/bootstrap/bootstrap.min.js' %}"></script>

		<!-- Vendor js _________ -->
		
		<!-- revolution -->
		<script src="{% static 'Main/vendor/revolution/jquery.themepunch.tools.min.js' %}"></script>
		<script src="{% static 'Main/vendor/revolution/jquery.themepunch.revolution.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.slideanims.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.layeranimation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.navigation.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.kenburn.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.actions.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/vendor/revolution/revolution.extension.video.min.js' %}"></script>

		<!-- Google map js -->
		<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZ8VrXgGZ3QSC-0XubNhuB2uKKCwqVaD0&callback=goMap" type="text/javascript"></script> <!-- Gmap Helper -->
		<script src="{% static 'Main/vendor/gmaps.min.js' %}"></script>
		<!-- owl.carousel -->
		<script type="text/javascript" src="{% static 'Main/vendor/owl-carousel/owl.carousel.min.js' %}"></script>
		<!-- mixitUp -->
		<script type="text/javascript" src="vendor/jquery.mixitup.min.js' %}"></script>
		<!-- Progress Bar js -->
		<script type="text/javascript" src="vendor/skills-master/jquery.skills.js' %}"></script>
		<!-- Validation -->
		<script type="text/javascript" src="vendor/contact-form/validate.js' %}"></script>
		<script type="text/javascript" src="vendor/contact-form/jquery.form.js' %}"></script>


		<!-- Theme js -->
		<script type="text/javascript" src="{% static 'Main/js/theme.js' %}"></script>
		<script type="text/javascript" src="{% static 'Main/js/map-script.js' %}"></script>

		</div> <!-- /.main-page-wrapper -->
	</body>
</html>

Agency/templates/Agency/Rejected_crime.html
{% extends 'agency/Head.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%  block content %}
    <br><br><br><br>
    <div id="tab">
        <br><br><center><h2>Rejected Crime</h2></center><br><br>
    <form action="" method="post">
        <table align="center" border="2">
            <tr>
                <th>User Name</th>
                <th>Crime Type</th>
                <th>Description</th>
                <th>Action</th>
            </tr>
            {% for i in C %}
            <tr>
                <td>{{i.user.name}}</td>
                <td>{{i.crimetype}}</td>
                <td>{{i.crime_description}}</td>
                <td><a href="{% url 'agency:Accept_Crime' i.id %}">Accept</a></td>
            </tr>
            {% endfor %}
        </table>
    </form>
    </div>
</body>
</html>
<br><br>
{% endblock content %}